config/routes.rb
Rails.application.routes.draw do
  resources :votes, only: [:create, :destroy]
  resources :discussions do
    resources :comments
  end
  resources :courses do
    resources :lessons do
      member do
        put :complete
      end
    end
  end
  resources :enrollments, only: [:create, :destroy]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'registrations'}
  resources :users

  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :votes, through: :comments
  belongs_to :user

  validates_presence_of :title, :content
  validates :title, length: {minimum: 5}
  validates :content, length: {minimum: 5}
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :set_discussion, only: [:show, :edit, :update, :destroy]

  # GET /discussions
  # GET /discussions.json
  def index
    @discussions = Discussion.all.order("created_at DESC")
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
  end

  # GET /discussions/new
  def new
    @discussion = current_user.discussions.build
  end

  # GET /discussions/1/edit
  def edit
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = current_user.discussions.build(discussion_params)
    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: 'Discussion was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /discussions/1
  # PATCH/PUT /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to @discussion, notice: 'Discussion was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to discussions_url, notice: 'Discussion was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discussion
      @discussion = Discussion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discussion_params
      params.require(:discussion).permit(:title, :content)
    end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
  def join_tags(discussion)
    discussion.tags.map { |t| t.name }.join(", ")
  end
end

app/views/discussions/_form.html.erb
  <%= form_for(@discussion) do |f| %>
    <% if @discussion.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@discussion.errors.count, "error") %> prohibited this discussion from being saved:</h2>

        <ul>
        <% @discussion.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <fieldset class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: "form-control" %>
    </fieldset>

    <fieldset class="form-group">
      <%= f.label :content %><br>
      <%= f.text_area :content, class: "form-control" %>
    </fieldset>
    <div class="actions">
      <%= f.submit 'Submit', class: "btn btn-primary" %>
    </div>
  <% end %>

app/views/discussions/edit.html.erb
<div class="container bg-white">
<h1>Editing Discussion</h1>

<%= render 'form' %>

<%= link_to 'Show', @discussion %> |
<%= link_to 'Back', discussions_path %>
</div>

app/views/discussions/index.html.erb
<div class="container">
<h1>Listing Discussions | <%= link_to 'New Discussion', new_discussion_path %></h1>
</div>

<% Discussion.all.each do |discussion| %>
  <div class="container">
    <div class="row" style="margin-top: 10px;">
      <div class="col-md-8 bg-white">
        <div class="media">
          <div class="media-left">
              <%= image_tag("pen") %>
          </div>
          <div class="media-body">
            <h3 class="media-heading font-1"><%= discussion.title %></h3>
            <%= link_to 'Show', discussion %>
            <% if discussion.user == current_user || current_user.admin? %>
              | <%= link_to 'Edit', edit_discussion_path(discussion) %>
            <% end %>
            <% if current_user.admin? %>
              | <%= link_to 'Destroy', discussion, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
         </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/discussions/new.html.erb
<div class="container bg-white">
  <h1>New Discussion</h1>

  <%= render 'form' %>

  <%= link_to 'Back', discussions_path %>
</div>

app/views/discussions/show.html.erb
<div class="container">
  <div class="row" style="padding-bottom: 10px;">
   <div class="col-md-9 bg-white">
      <h2 class="font-2"><%= @discussion.title %></h2>
      <hr>
      <h4 class='font-3'><%= @discussion.content %></h4>
      <br>
      <p>Posted by <%= @discussion.user.email %> <%= time_ago_in_words(@discussion.created_at) %> ago</p>

      <div class="links btn-group">
        <%= link_to "Back", root_path, class: "btn btn-default" %>
        <% if @discussion.user_id == current_user.id || current_user.admin? %>
          <%= link_to "Edit", edit_discussion_path(@discussion), class: "btn btn-default" %>
          <%= link_to "Delete", discussion_path(@discussion), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
        <% end %>
      </div>
      <h3>Reply to question:</h3>
      <!-- renders the comments form -->
      <%= render 'comments/form' %>
     </div>
    </div>
    <hr>
    <%= render @discussion.comments.order_by_vote %>
</div>

<!-- renders the _comment.html.erb partial file. -->