config/routes.rb
Rails.application.routes.draw do
  resources :votes, only: [:create, :destroy]
  resources :discussions do
    resources :comments
  end
  resources :courses do
    resources :lessons do
      member do
        put :complete
      end
    end
  end
  resources :enrollments, only: [:create, :destroy]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'registrations'}
  resources :users

  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :discussion
  has_many :votes

  validates :content, presence: true, length: {minimum: 5} 

  scope :order_by_vote, -> { joins(:votes).group(:comment_id).order("count(comment_id) desc")}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_discussion, only: [:create, :edit, :update, :destroy]
  before_action :set_comment, only: [:edit, :update, :destroy]

  def create
    @comment = @discussion.comments.create(comment_params)
    @comment.user_id = current_user.id
    @comment.votes.create(user_id: current_user.id)

    if @comment.save
      redirect_to discussion_path(@discussion)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to discussion_path(@discussion)
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_to discussion_path(@discussion)
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end

    def set_discussion
      @discussion = Discussion.find(params[:discussion_id])
    end

    def set_comment
      @comment = @discussion.comments.find(params[:id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="panel panel-default">
    <div class="panel-body">
         <button type="button" class="btn btn-primary" aria-label="Left Align">
           <span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span>
           <%= link_to 'Up Vote', votes_path(comment_id: comment), method: :post, class: "font-white" %>
           <span class="badge"><%= comment.votes.count %></span>
        </button>
         <hr>
         <p class="comment-content"><%= comment.content %></p>
         <p class="comment-posted-by">Posted by <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago</p>
         <% if comment.user_id == current_user.id || current_user.admin? %>
           <div class="panel-footer">
             <%= link_to "Edit", edit_discussion_comment_path(comment.discussion, comment) %>
             <%= link_to "Delete", discussion_comment_path(comment.discussion, comment), method: :delete, data: { confirm: "Are you sure?" } %>
           </div>
         <% end %>
    </div>
</div>

app/views/comments/_form.html.erb
<div style="padding:5px;">
<%= form_for([@discussion, @discussion.comments.build]) do |f| %>
  <fieldset>
    <%= f.text_area :content, label: "Comment", class: "form-control" %>
  </fieldset>
  <%= f.submit 'Create Comment', class: "btn btn-primary" %>
<% end %>
<div>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= form_for([@message, @comment]) do |f| %>
  <%= f.text_field :body, label: "Comment" %>
  <%= f.submit %>
<% end %>