config/routes.rb
Rails.application.routes.draw do
  resources :votes, only: [:create, :destroy]
  resources :discussions do
    resources :comments
  end
  resources :courses do
    resources :lessons do
      member do
        put :complete
      end
    end
  end
  resources :enrollments, only: [:create, :destroy]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'registrations'}
  resources :users

  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]
  has_many :enrollments
  has_many :courses, through: :enrollments
  has_many :votes
  has_many :discussions
  enum role: [:user, :editor, :admin]
  after_initialize :set_default_role, :if => :new_record?


  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first

    if user
     return user
    else
     registered_user = User.where(:email => access_token.info.email).first
     if registered_user
       return registered_user
     else
       user = User.create(
       name: data["name"],
       email: data["email"],
       provider:access_token.provider,
       uid: access_token.uid ,
       password: Devise.friendly_token[0,20]
       )
     end
    end
  end

  private

  def set_default_role
    self.role ||= :user
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize(User)
  end

  def show
    @user = current_user
    authorize(@user)
  end

  def update
    @user = User.find(params[:id])
    authorize(@user)
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/views/users/index.html.erb
<% @users.each do |user| %>
  <div class="container" style="padding-top: 10px;">
    <div class="row">
      <div class="col-md-9 bg-white">
        <div class="media">
          <div class="media-left">
            <%= image_tag("pen") %>
          </div>
          <div class="media-body">
            <h4 class="media-heading"><%= user.name %></h4>
            <h4><%= link_to user.email, user %></h4>

            <%= form_for(user) do |f| %>
             <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
             <td>
             <%= f.submit 'Change Role', class: "btn btn-danger" %>
             </td>
           <% end %>
           <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button') unless user == current_user %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<script>
  /* script fix turbolinks not resizing main and sidebar */
  $('.root-main').height($('.root-sidebar').height());
  $(document).ready(function(){
    $('.root-main').height($('.root-sidebar').height());
  });
</script>

<div class="container">
<div class="row">
    <div class="col-md-8 bg-white root-main">
                 <h4>Welcome</h4>
                 <hr>
                 <% if @user.courses.count == 0 %>
                   <h4 class="font-2 alert-info">Enroll in some courses.</h4>
                 <% else %>
                   <h4 class="font-2 alert-success">Start learning by clicking Start Lesson.</h4>
                <% end %>
    </div>

    <div class="col-md-3 col-md-offset-1 bg-white root-sidebar">
              <h4>Courses</h4>
              <ul class="list-group">
                 <% Course.all.each do |course| %>
                   <li class="list-group-item">
                     <p class="font-3"><%= course.title %></p>
                     <%= button_to 'Enroll', enrollments_path(course_id: course) %>
                   </li>
                 <% end %>
              </ul>
      </div>
    </div>
</div>

<% if @user.courses.count != 0 %>
  <div class="container">
    <h1 class="font-1">Your Courses</h1>
  </div>

  <% @user.courses.each do |course| %>
    <div class="container">
      <div class="row" style="margin-top: 10px;">
        <!-- begin course panels -->
        <div class="col-md-8 bg-white">
          <div class="media">
            <div class="media-left">
                <%= image_tag("badge") %>
            </div>
            <div class="media-body">
              <h3 class="media-heading font-1"><%= course.title %></h3>
              <p class="font-3"><%= course.description %><p>
              <p class="font-2"><%= link_to "Start Lesson", course_path(course) %><p>
              <% if current_user.admin? %>
                <%= link_to 'Delete', enrollment_path(course_id: course), method: :delete %>
              <% end %>
            </div>
          </div>
        </div>
        <!-- end course panels -->
      </div>
    </div>
  <% end %>
<% end %>