config/routes.rb
Rails.application.routes.draw do
  resources :votes, only: [:create, :destroy]
  resources :discussions do
    resources :comments
  end
  resources :courses do
    resources :lessons do
      member do
        put :complete
      end
    end
  end
  resources :enrollments, only: [:create, :destroy]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'registrations'}
  resources :users

  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :discussion
  has_many :votes

  validates :content, presence: true, length: {minimum: 5} 

  scope :order_by_vote, -> { joins(:votes).group(:comment_id).order("count(comment_id) desc")}
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :enrollments
  has_many :users, through: :enrollments
  has_many :lessons, dependent: :destroy

  validates_presence_of :title, :description
  validates :title, length: {minimum: 5}
  validates :description, length: {minimum: 5}
  
  def lesson
    Lesson.new
  end

  def lesson_attributes=(attributes)
    existing_lesson = self.lessons.find_by(title: attributes["title"])
    if existing_lesson.nil?
      self.lessons.build(attributes)
    end
    existing_lesson
  end
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :votes, through: :comments
  belongs_to :user

  validates_presence_of :title, :content
  validates :title, length: {minimum: 5}
  validates :content, length: {minimum: 5}
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :course
  belongs_to :user

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :course
  
  scope :locked, -> { where(locked?: true) }

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :discussion
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]
  has_many :enrollments
  has_many :courses, through: :enrollments
  has_many :votes
  has_many :discussions
  enum role: [:user, :editor, :admin]
  after_initialize :set_default_role, :if => :new_record?


  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first

    if user
     return user
    else
     registered_user = User.where(:email => access_token.info.email).first
     if registered_user
       return registered_user
     else
       user = User.create(
       name: data["name"],
       email: data["email"],
       provider:access_token.provider,
       uid: access_token.uid ,
       password: Devise.friendly_token[0,20]
       )
     end
    end
  end

  private

  def set_default_role
    self.role ||= :user
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment

  def up_vote
    self.comment.increment(:vote_count, by = 1)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:title, :description, lesson_attributes: [:title, :content])
    end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
    render :index
  end

  def speech
    render :speech
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize(User)
  end

  def show
    @user = current_user
    authorize(@user)
  end

  def update
    @user = User.find(params[:id])
    authorize(@user)
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @vote = current_user.votes.find_by(comment_id: params[:comment_id])
    if @vote.nil?
      @vote = current_user.votes.create(comment_id: params[:comment_id]).up_vote
      redirect_to request.referrer
    else
      redirect_to request.referrer
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
  def join_tags(discussion)
    discussion.tags.map { |t| t.name }.join(", ")
  end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/skill_helper.rb
module SkillHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if user_signed_in? %>
        <a class="navbar-brand text-white font-1" href=<%= user_path(current_user) %>>
      <% else %>
        <a class="navbar-brand text-white font-1" href="/">
      <% end %>
        Rienery
        <span class="glyphicon glyphicon-grain" aria-hidden="true"></span>
      </a>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if user_signed_in? %>
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", user_path(current_user) %></li>
        <li><%= link_to "Course", courses_path %></li>
        <li><%= link_to "Discussion", discussions_path %></li>
      </ul>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> <%= current_user.name %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if current_user.admin? %>
            <li><a href="/users">Users Path</a></li>
            <% end %>
            <li><%= link_to "Course", courses_path %></li>
            <li><%= link_to "Discussion", discussions_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link href="http://fonts.googleapis.com/css?family=Roboto|Roboto+Condensed|Alegreya:700" rel="stylesheet" type="text/css" />
  <title>Rienery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "/layouts/nav" %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <% if message_type == "alert" %>
        <% alert_class = "alert-danger" %>
      <% else %>
        <% alert_class = "alert-info" %>
      <% end %>
    <div id="flash" class="alert <%= alert_class %>"><%= message %></div>
    <% end %>
  </div>
  <%= yield %>

</body>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<script>
  /* script fix turbolinks not loading nav transition*/
  $('ul.nav li.dropdown').hover(function() {
    $(this).find('.dropdown-menu').stop(true, true).delay(50).fadeIn(500);
  }, function() {
    $(this).find('.dropdown-menu').stop(true, true).delay(50).fadeOut(500);
  });
  $(document).ready(function(){
    $('ul.nav li.dropdown').hover(function() {
      $(this).find('.dropdown-menu').stop(true, true).delay(50).fadeIn(500);
    }, function() {
      $(this).find('.dropdown-menu').stop(true, true).delay(50).fadeOut(500);
    });
  });
</script>
</html>

app/views/layouts/media_card_6.html.erb
<div class="container">
  <div class="row">
    <!-- begin course panels -->
    <div class="col-md-6 bg-white">
      <div class="media">
        <div class="media-left">
          <a href="#">
            <%= image_tag("badge") %>
          </a>
        </div>
        <div class="media-body">
          <h4 class="media-heading">Media heading</h4>
          <p>Something this tex is going to talke about. asldfjasldfjasldkjfalskdfjklasdfjlkasjfklasjdfkj<p>
        </div>
      </div>
    </div>
    <!-- end course panels -->
  </div>
</div>